### ISSUE TITLE
PLANET-5509 Disable xmlrpc

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#101]
xmlrpc is enabled in all of our instances (is enabled by default in WP). We probably don't rely on that anywhere in our code and it's safe to disable it. Having this enabled is a target for brute-force attacks.

**Tasks**
- Investigate if disabling it has any side effects.
- Disable it preferably through code (not plugin, but maybe check its code).

```
Reporter: nroussos
Sections: Security
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by mleray** [comment]
Solved with https://github.com/greenpeace/planet4-master-theme/pull/1289
