### ISSUE TITLE
PLANET-5397 Sync translatable strings to language po files

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#102]
When looking at the source code (and the editor) there are a lot of possibly translatable strings. These strings are not present in the .pot language files, so are missing from the strings that people can translate.

**Tasks**
- Look for translatable strings that are missing from .po files in both app repos and add them.
- Use [poedit](https://poedit.net/) to generate the .mo files.
- Write a documentation page on how we create .po files.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31529/Screenshot+from+2020-08-11+10-29-55+-+Oscar+Keur.png)
![Screenshot](https://jira.greenpeace.org/secure/attachment/31528/Screenshot+from+2020-08-11+10-31-12+-+Oscar+Keur.png)
```
Reporter: okeur
Sections: Translations
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme), [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by comzeradd** [comment]
Done in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/383
