### ISSUE TITLE
PLANET-4590 Image block: Photo credit/copyright is not visible in the editor

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#103]
In the editor, when an Image is added to post the caption is there but the credit/copyright text is missing. It's visible though in the frontend. That can be confusing for editors.

 

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/30178/credi-photo-available-in-frontend.PNG)
![Screenshot](https://jira.greenpeace.org/secure/attachment/30177/no-credit-photo-in-backend.PNG)
```
Reporter: aradu
Sections: Gutenberg
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme), [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by janocano** [comment]
hmmm on master i am seeing the copyright logo show up! 
![image](https://user-images.githubusercontent.com/34040871/94852802-6bc86500-03f8-11eb-944d-42c6de0f8373.png)

**Comment by sagarsdeshmukh** [comment]
> hmmm on master i am seeing the copyright logo show up!
> ![image](https://user-images.githubusercontent.com/34040871/94852802-6bc86500-03f8-11eb-944d-42c6de0f8373.png)

Hi @janocano , Looks like you were tested for gallery block image, indeed for gallery block the image credit and copyright text are visible. The issue is reproducible for image block in block editor :)

**Comment by comzeradd** [comment]
This was fixed at https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/461
