### ISSUE TITLE
PLANET-5538 Use h1 for the Search Results title

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#104]
It's a good practice for pages to have the top headline as h1. In the Search Page that's the "(n) results for '<term>'. 
eg. https://www.greenpeace.org/international/?s=climate&orderby=_score

**Tasks**
- Change [that title](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/search.twig#L14) from h2 to h1

```
Reporter: nroussos
Sections: 
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by oekeur** [comment]
That would give strange results SEO wise I guess, right?
How about:
`<h1>Search for [term]</h1>`
`<h2>x results found<h2>`
?

**Comment by emmarise** [comment]
Our team changed it just now, I think @powersaudrey25 has already pull request.

**Comment by Inwerpsel** [comment]
> Our team changed it just now, I think @powersaudrey25 has already pull request.

Ok, can this one be closed?

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-master-theme/commit/4186372c4c5caddebd393a4bacc3a37321929e6a
