### ISSUE TITLE
Help designing the "Be Right Back" page

### ISSUE THREAD

**Issue by IlBrizzo** [greenpeace/planet4#106]
Our IT colleagues can now offer a standardized “_Be right Back_” page (see [](https://brb.p4.greenpeace.org) ), to provide a **temporary landing page whenever any web property of our toolset is temporarily offline**. 

A redirect to this page could be set up both on demand and in case of sudden unavailability of a Greenpeace web property, not only to P4 sites, but to any Wordpress, Open Social, ControlShift, donation pages and so on..

### We need help to design this basic landing page... 

Feel creative? Familiar with Greenpeace's  branding / design? Feel free to provide design guidance for this (very basic) landing page.

## Relevant documentation:
[Here's the short Project brief](https://docs.google.com/document/d/1MEsodA0E3VOGic-4b0KYLxVHpFpY85fK_TUPREDtGfs/edit?usp=sharing), with scope, UX and analytics setup. Please use / consume it! 

In this document, we summed up the tiny bits of work that should be done (see "Redesign" part), involving image, gp logo, primary colours, fonts and text.

Obviously anyone familiar with Greenpeace branding / Design approach can recommend any other relevant design change.

## Estimated length of task:
2h max 

### Timeline for task:
This task should ideally be completed by end of October. 

### Example of similar work:
The global landing page (which will be the destination of the BRB page :) ) https://www.greenpeace.org/global/  

## Help:
Please comment in the ticket or write to planet4-pm-group@greenpeace.org if you need any info! The team will get back to you..

**Comment by lucia-garcia** [comment]
This is pretty cool... Also pretty old. Are you still looking for volunteers?
I can see the old layout is not active anymore (https://brb.p4.greenpeace.org/ 
)
