### ISSUE TITLE
PLANET-5441 Hashtag cuts off text for social media sharing

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#109]
Example Page:  
https://www.greenpeace.org/canada/en/story/41373/why-you-have-to-say-gnlnonmerci-before-september-14/

Description of the issue: The title of this page has a hashtag (#). By default, when somebody clicks the Twitter button at the top of the page, the tweet only contains the title text that comes before the hashtag. The text following the hashtag is cut off. Effectively, this makes us unable to use hashtags for social sharing. The full title can be displayed in the tweet if it is placed in Open Graph/Social Fields, but not if a hashtag is included.

**Tasks**
- Fix the bug by making sure the whole is being used in the share text
- Check if this affects the rest of the share buttons

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31576/Screen+Shot+2020-08-24+at+2.58.51+PM+-+Lucas+Silbernagel.png)
```
Reporter: lsilbern
Sections: Social Media
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by lovlin-thakkar** [comment]
Hi, please check this pull request I've opened: https://github.com/greenpeace/planet4-master-theme/pull/1216
