### ISSUE TITLE
[Wiki] 404 page

### ISSUE THREAD

**Issue by 45kb** [greenpeace/planet4#11]
I don't know if it's wanted but this link in the wiki is 404

https://workfor.greenpeace.org/vacancies/details/php-developer/

Would be better to inform "The position is no more available" instead of a 404 👍

**Comment by koyan** [comment]
Thanks Filippo. The website where the job postings happen is in a different application than planet4, so we don't control it's beheaviour. I will pass on your suggestion to it's administrators. Since it is a ready made solution though, I doubt they have any control over it's beheaviour.

**Comment by 45kb** [comment]
@koyan since I'm here i give you one more thing you maight be interested to report it to the admins  👍 

Mac Sierra OS / Safari

![schermata 2018-05-24 alle 15 37 37](https://user-images.githubusercontent.com/7761650/40489165-cfa4161e-5f68-11e8-8cb6-b7a71145637c.png)

Mac Sierra OS / Chrome
![schermata 2018-05-24 alle 15 37 52](https://user-images.githubusercontent.com/7761650/40489180-d459a1ce-5f68-11e8-82d1-3e7fba2d1bfb.png)

In case the navbar logo transition should be fixed a little :P (this is on Safari and Mac Sierra OS)

https://imgur.com/CucSvzu

**Comment by LauraHilliger** [comment]
Thanks for filing this! We're revamping this repo, and I see this issue is a couple years old. It also seems that @koyan took care of this request. I'm going to close this issue.
