### ISSUE TITLE
GPLux ChildTheme fixes

### ISSUE THREAD

**Issue by LiseBocklerGP** [greenpeace/planet4#111]
## Brief summary of task: 
Greenpeace Luxembourg ChildTheme causes many issues during GPI releases because design changes interfere with our chiltheme (buttons break, colours change back to MasterTheme, etc). As GPLux we do not have our own developper, only 1 webbie (me) so we can just act on superficial things as custom CSS, that I keep adding up with "!important" mentions to overrite the existant. This is not viable, so we would need a great kind dev (THANK YOU DEAR) to clean up our Childtheme, add new CSS and 2 low fixes.

### Objectives of task: 
**priority order :**
1. Integrate [this custom CSS](https://docs.google.com/document/d/1HIHVJKWDY3KWkUxT93fP9HJ4HgW8jBzJ2HudDny3fUM/edit#)
2. Clean up our ChildTheme removing everything that seems useless (old code, pieces of master theme that could interfere with releases...) 
3. Footer : Fix the country selector and move it back in the header (as GPI)
4. Contact form feature : exclude symbols in Name fields + add character limits to avoid bot spamming 

## Relevant documentation:
Custom CSS here : https://docs.google.com/document/d/1HIHVJKWDY3KWkUxT93fP9HJ4HgW8jBzJ2HudDny3fUM/edit#

## Estimated length of task: 
(can't tell, I hope not too long)

### Timeline for task: 
whenever possible, not urgent but important <3

## Help: 
please contact me at lise.bockler@greenpeace.org or Lise Bockler on SLACK for any question. **WE ARE SINCERLY GRATEFUL** for your help. Thank you, anonymous saviour.

**Comment by suzi-greenpeace** [comment]
being picked up by p4 team

**Comment by LiseBocklerGP** [comment]
Fantastic thank you !

*Lise Bockler *
*Communication Manager*
Greenpeace Luxembourg
