### ISSUE TITLE
PLANET-5259 EN Form Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#113]
Then EN Form has a few minor issues.

- The text on the left side could maybe have a **role=text** attribute to make sure is not read separately if it has links in between.
- The **Country** field's label, is read after the field, it should be read before.
- The text in the checkboxes can probably use **role=text** also to ensure is not read as separate bits of content if it has links in the middle.
- We should make sure the Thank You message is properly announced, perhaps using **aria-live**.

```
Reporter: pcuadrad
Sections: Block: EN Form
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by mleray** [comment]
This should be done after the block has been converted to WYSIWYG ([PLANET-4814](https://jira.greenpeace.org/browse/PLANET-4814))

**Comment by isabelle-np** [comment]
I can work on this
