### ISSUE TITLE
PLANET-5252 Social Media Block Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#115]
As with the Media Block, the Social Media block embeds content from other places, so the accessibility of that content depends on them.

There's not much to do here, except maybe we can add a field here as well, an Accessibility text field to let editors add some additional info about the embedded content in case the accessibility of the provider (Twitter, Facebook, etc) sucks. Then we render that content in an **visually-hidden** element so it's only visible to screen readers

**Tasks**
- Investigate if we can pick up the original description of the embed to use
- Otherwise add a non-mandatory field for editors

```
Reporter: pcuadrad
Sections: Block: Social Media
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by mleray** [comment]
This block is broken at the moment ([PLANET-5994](https://jira.greenpeace.org/browse/PLANET-5994)), so this should be done after it's fixed
