### ISSUE TITLE
PLANET-5212 Columns Block Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#117]
Make sure the Columns block is readable by Screen Readers.

Known issues so far:

Redundant links are often used in visual design but for a SR it means a link will be read two or three times, for example, in the Icons style, the column Icon and the column Title have the same link. We should hide the icon to the SR using aria-hidden.

**Tasks:**
- Hide icons in the Icons style (see `LAYOUT_ICONS` conditions in this [file](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Columns/Columns.js)).
- Find other redundant links and preserve only the one that makes more sense in an audible flow.
- Test with a SR for other possible glitches or errors in the flow.

[Help doc](https://docs.google.com/document/d/1VGkZ5T_SdAfLa-KNfNJVIBiIJxItG2zbWjwqfPLFZxE/)

```
Reporter: pcuadrad
Sections: 
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

### Testing
Add a Columns block to a page and test out the different styles with a screen reader, with images too when applicable. For the [Tasks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Columns/ColumnsTasks.js) style, please also test the block on mobile as it is a very different layout. You can also check out the [docs](https://planet4.greenpeace.org/act/columns/) for more details.

JIRA Ticket: https://jira.greenpeace.org/browse/PLANET-5212

**Comment by Tendol** [comment]
I can work on this.

**Comment by GP-Dan-Tovbein** [comment]
@Tendol go for it! 👍

**Comment by GP-Dan-Tovbein** [comment]
@Tendol here is the ticket [url](https://jira.greenpeace.org/browse/PLANET-5212) if you need more information. Also added to the PR's description.
