### ISSUE TITLE
PLANET-5246 Cookies block Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#119]
The [Cookies block](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Cookies/CookiesFrontend.js) looks ok, but maybe it could use a test with NVDA or Orca screen readers, I only tested VoiceOver.

The main ingredients to watch in the Cookies block are the checkboxes, but there is separate Checkbox Accessibility issue for them:

JIRA Ticket: https://jira.greenpeace.org/browse/PLANET-5245

```
Reporter: pcuadrad
Sections: Block: Cookies
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

### Testing
You can add a Cookies block to a page and test it out with one of the screen readers mentioned above. You can also check out the [docs](https://planet4.greenpeace.org/act/block-cookies/) for more details.

**Comment by mleray** [comment]
This is currently blocked since it makes more sense to do it after redesigning the Cookies ([PLANET-6075](https://jira.greenpeace.org/browse/PLANET-6075)).
