### ISSUE TITLE
[Wiki] Vertical space between items

### ISSUE THREAD

**Issue by 45kb** [greenpeace/planet4#12]
You could give a vertical space between top elements in your https://wiki.greenpeace.org website 👍 

![screenshot](https://i.imgur.com/4zXGVmz.png)

Chrome version: latest
OS: OSX

**Comment by koyan** [comment]
Thanks, I will pass it on to the team who is maintaining the wiki.greenpeace.org website.

**Comment by 45kb** [comment]
@koyan sorry again just saw something i don't understand.
If you open greenpeace.org
i think the logo/name of the org is totally unreadable because is green on blue

![schermata 2018-05-22 alle 15 13 00](https://user-images.githubusercontent.com/7761650/40377817-25014adc-5df2-11e8-83ac-54dfd71252de.png)

Not here to criticize just hope to be of help.

Tried something on the fly, wouldn't be better something like this?
There are many many variants you could use instead of the one choosed IMHO.

![schermata 2018-05-22 alle 19 06 05](https://user-images.githubusercontent.com/7761650/40378242-44805078-5df3-11e8-8147-911c1bbe9082.png)
![schermata 2018-05-22 alle 19 05 58](https://user-images.githubusercontent.com/7761650/40378244-44b6d2e2-5df3-11e8-8d33-9f1b084260e8.png)

**Comment by koyan** [comment]
Hi Filippo,
I have passed your comments to the design team. 

You can read more about the colour choices at: 
https://medium.com/planet4/greenpeace-is-a-colourful-organisation-5f3b96e4f01
The team tested a lot of things and took into account a lot of things. The design is a continuous project and we are expecting a lot of iterations in the future. (Based on analysis and data)

Konstantinos

**Comment by LauraHilliger** [comment]
LOL @45kb What's really funny is that I'm RIGHT THIS SECOND filing front end tickets for some changes that get rid of that color!

**Comment by 45kb** [comment]
@koyan that's understandable, thanks for the link, did not notice that.

@LauraHilliger ☮️
