### ISSUE TITLE
PLANET-5250 Take Action Boxout Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#123]
The Take Action Boxout is under UX revision, so I would consider checking with Magali on this task.

There are some issues with hashtags and the CTA not showing unless you hover the element, refer to the Hashtags a11y ticket and the Covers Block a11y ticket to know more about those issues and how to address them.

As for this block specifically, the main issue is that it is rendered inline, but showed on the side. So for the screen reader, it IS inline, for example, if the block lives between two other blocks, it would be read aloud when going through those blocks.

The simplest (non-coding) solution would be to tell editors to make sure they add the TA boxout on the end of the page/post in the editor.

The elegant thing would be to make it an "aside" element, and make sure it's render as a child of the body, or the main page/post content element. This can be done using Twig `{% blocks %}` if done in the server side, but if we migrate it to the client with React, we'll need to maybe make a special case for this block in the frontend renderer (`frontendIndex.js`) to make sure it's attached to the body or to a new element we assign for it.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31373/take-action-boxout.gif)
```
Reporter: pcuadrad
Sections: Block: Take Action
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

### Testing
Add a Take Action boxout block to a page and test it out with a screen reader. You can also check out the [docs](https://planet4.greenpeace.org/act/block-take-action-boxout/) for more details.

**Comment by mleray** [comment]
This issue is currently blocked, since we first want to decide on a new design and convert the block to WYSIWYG ([PLANET-4812](https://jira.greenpeace.org/browse/PLANET-4812)).
