### ISSUE TITLE
PLANET-5251 Media Block Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#124]
The Media block embeds content from other sources, sometimes using an iframe, or a native media player in case it's a direct link to an mp3, wav, or mp4 file.

So in most cases, the accessibility of that content does not depend on us. 

However I guess we can improve the UX a bit on our side, suggestions: 
 - In the case of the MP4 file ([MediaElementVideo component](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Media/MediaElementVideo.js#L1)), as the user can add an picture from the media library as cover image (`videoPoster` prop), add the caption in a **visually-hidden** div so it can be read by the screen reader. You'll need to add the caption to the [media data](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/classes/blocks/class-media.php#L87).

 - For the rest of the cases, add an extra field to the Media block in the [backend](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Media/MediaEditor.js), added also as a **visually-hidden** element in the [frontend](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Media/MediaFrontend.js), to let editors describe the embedded content to visually impaired users.

The rest depends on the inserted element, the provider (Youtube, Vimeo, Soundcloud), or the browser in case of native controls (mp3, mp4, etc).

```
Reporter: pcuadrad
Sections: Block: Media
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

### Testing
You can test your changes on local by adding a Media block to a page and checking the different media types with a screen reader. You can also read the [docs](https://planet4.greenpeace.org/act/block-video-media/) for more details.

JIRA ticket: https://jira.greenpeace.org/browse/PLANET-5251

**Comment by akankshakmr174** [comment]
I can work on this.

**Comment by GP-Dan-Tovbein** [comment]
Go for it!

**Comment by GP-Dan-Tovbein** [comment]
@akankshakmr174 I've updated the ticket with the JIRA ticket for more information :)

**Comment by akankshakmr174** [comment]
@GP-Dan-Tovbein Thank you!
