### ISSUE TITLE
Add an option for a second button on each slide of the carousel header block

### ISSUE THREAD

**Issue by LucasSilbernagel** [greenpeace/planet4#126]
##  Feature summary

For the carousel header block, it would be nice to have the option to add a second button to each slide. I was able to achieve this for GPCA by copying the carousel header block from the browser dev tools along with a couple of necessary script tags, duplicating the existing button on one of the slides, and pasting all of that code into a custom HTML block on the page in P4. It works, but is obviously a hacky solution, and sometimes causes bugs with the header navigation menu, especially on mobile.

## Additional context

See screenshot.

<img width="1278" alt="Screen Shot 2020-12-07 at 10 08 57 AM" src="https://user-images.githubusercontent.com/57023164/101367888-8560af80-3874-11eb-9f68-dfe0990f210d.png">

**Comment by comzeradd** [comment]
Thanks @LucasSilbernagel. Closing this here, so it's reviewed first from a Product/Design perspective as an [Idea](https://planet4.greenpeace.org/idea/add-an-option-for-a-second-button-on-each-slide-of-the-carousel-header-block/).
