### ISSUE TITLE
PLANET-5387 Campaigner User Role missing from Author dropdown field

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#127]
Description of the issue: I am not able to reassign a Campaign page to a user with the role of Campaigner. Their name does not appear in the dropdown list.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31515/Screenshot+2020-08-05+at+15.56.01+-+Kelli+Tolen.png)
![Screenshot](https://jira.greenpeace.org/secure/attachment/31514/Screenshot+2020-08-05+at+15.57.45+-+Kelli+Tolen.png)
```
Reporter: ktolen
Sections: Admin Panel
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Fixed at greenpeace/planet4-master-theme#1257
