### ISSUE TITLE
PLANET-5264 Covers block: Display issue on mobile device

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#128]
[Example Page](https://www.greenpeace.org/international/tag/oil/)

Description of the issue: The 3rd cover should be partially visible on mobile as per the mockup attached.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/32182/covers_block.jpg)
![Screenshot](https://jira.greenpeace.org/secure/attachment/32181/Screenshot+2020-06-30+at+13.06.08+-+Kelli+Tolen.png)
```
Reporter: ktolen
Sections: Block: Covers
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/462
