### ISSUE TITLE
PLANET-5489 Happypoint mailing list iframe toggle doesn't work

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#129]
There is currently a small bug in the Happypoint block: if the editor enters an iframe url in the input, the iframe is shown even if the `mailing list iframe` checkbox is unchecked. This is not the expected behaviour, at least according to the help text below the input!

*Tasks*
- Implement one of the two options, in priority:
  1. disabling the iframe url field when the toggle button is Off. 
  2. automatically switching On the toggle button as soon as users enter a Iframe url in the field
- Make sure existing content is still displayed.
- If toggle button switch to off, then iframe not displayed in the frontend

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/32173/Screenshot+2020-09-16+at+08.51.29.png)
```
Reporter: mleray
Sections: Block: Happy Point
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by mleray** [comment]
Fixed in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/471
