### ISSUE TITLE
[Audits] Generic suggestion

### ISSUE THREAD

**Issue by 45kb** [greenpeace/planet4#13]
Hi all :)

One thing i wanted to suggest (if not tried it yet) try run the Google Chrome devtools "Audits"  on greenpeace.org

![schermata 2018-07-25 alle 11 54 02](https://user-images.githubusercontent.com/7761650/43194687-48b6db66-9003-11e8-91d1-62ddf3e6c8f2.png)

This should generate for you a series of helpful reports :)

Also the Google Pagespeed  insights is a great tool to optimize the website at best.

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fgreenpeace.org%2F&tab=desktop

Keep up the good job  👍

**Comment by koyan** [comment]
Thanks for the suggestion. To tell the truth I didn't know about that tool. I was doing similar tests using the google pagespeed tool, but this one seems to be checking more things. 
Thanks we will use it to see what we can impove.

**Comment by 45kb** [comment]
@koyan glad if it's of help! There are things you can easily improve and you'll benefit!

**Comment by LauraHilliger** [comment]
Thanks for filing this too! We're revamping this repo, and I see this issue is a couple years old. It also seems that @koyan took care of this request. I'm going to close this issue.
