### ISSUE TITLE
PLANET-5760 Remove jQuery code from load_more.js

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#134]
Rewrite all jquery code in `assets/src/js/load_more.js` with vanilla JS.

**Components**
* `setupLoadMore()`  runs an ajax request based on button dataset. Used in author and taxonomy templates.
* `fadeOut()` could be done in CSS ? The rest has to be in vanilla JS.

```
Reporter: fhernand
Sections: Performance
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by aeisenberg** [comment]
I'll take a look at this. Please assign to me.

There is a small issue here. This line:

```
load_more.off('mousedown touchstart').on('mousedown touchstart', function (e) {
```

The call to `off` will remove relevant jquery event handlers. If we try to remove jquery from this file, jquery event handlers will not be removed from the `load_more` dom elements. It's likely a low chance of anything bad happening, but thought I'd bring it up.

**Comment by aeisenberg** [comment]
The solution I am working on uses `fetch`. Are we able to use this, or do we need to support older browsers?

**Comment by lithrel** [comment]
Hi @aeisenberg, no problem for `fetch` :+1:
