### ISSUE TITLE
PLANET-5868 Update Table block caption styles

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#136]
The captions for the Table block should have the same styles as the Image block's captions, both in the frontend and in the editor (the center one, we don't have different caption alignment options for the Table block). 
- [Table styles](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/styles/blocks/core-overrides/Table.scss)
- [Image styles](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/styles/blocks/core-overrides/Image.scss)

**Tasks**
- Use same caption style as the Image block

**Screenshots**
- Table:
![Screenshot](https://jira.greenpeace.org/secure/attachment/32270/Screenshot+2021-01-15+at+14.25.32.png)
- Image:
<img width="962" alt="Screenshot 2021-05-04 at 09 10 57" src="https://user-images.githubusercontent.com/6949075/116970658-aa890b00-acb8-11eb-944e-523fcdeede37.png">

```
Reporter: mleray
Sections: Gutenberg, Styling/Theme
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by kritisingh1** [comment]
I'd like to take a look at this issue. Thanks!
