### ISSUE TITLE
PLANET-5758 Remove jQuery from header.js

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#137]
Rewrite all jquery code in `assets/src/js/header.js` (in [master-theme](https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/js/header.js)) with vanilla JS.

**Components**
- `setupHeader()` manages the navbar interactions.

```
Reporter: fhernand
Sections: Performance
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Testing**
The navbar (i.e. the top header with "Act", "Explore" etc) should behave the same as before (also on mobile): you can check the [GPI website](https://www.greenpeace.org/international) for comparison.

**Comment by himanshu007-creator** [comment]
Hi I would like to work on this issue!

**Comment by comzeradd** [comment]
Hi @himanshu007-creator, thank you for wanting to contribute 💚

As a starting point here is our documentation with instructions on how to setup your local development environment:
https://support.greenpeace.org/planet4/

**Comment by comzeradd** [comment]
Hey @himanshu007-creator. Do you require any assistance?

**Comment by himanshu007-creator** [comment]
> Hey @himanshu007-creator. Do you require any assistance?

Hi! I am clear with the issue and will work on it soon, have exams tomorrow 😅 so sorry for the delay

**Comment by comzeradd** [comment]
Done in https://github.com/greenpeace/planet4-master-theme/pull/1559
