### ISSUE TITLE
[Input] Desktop app

### ISSUE THREAD

**Issue by 45kb** [greenpeace/planet4#14]
Hi all,
Just got in mind to ask if you ever considered to build a simple Desktop app using Electron framework, it would be that simple https://github.com/electron/electron-quick-start

I believe it could give you inputs and engage even more people/donations through Desktop apps and app stores.

It could contain anything inside, i.e: 
- a News Reader with all the GP news in realtime (videos, photos, media ...)
-  a social feed (twitter, facebook etc...) 
- a donate button
- etc ...

The API is all Javascript/NodeJS, won't take too much time for a solid app to run on Desktops.

The same codebase/app will run on Linux, Windows and OSX as a proper desktop app.

For the Mac users it could become even a really comfortable [Tray app](https://github.com/kevinsawicki/tray-example) that could look like this:

![](https://raw.githubusercontent.com/maxogden/menubar/HEAD/screenshot.png)

Would be a new sector to cover i believe, if you don't yet have something in this way.

I hope it's not something embarrassing or out of your final purpose, just thought to give an input :)

**Comment by 45kb** [comment]
BTW this is what happens when i search "Greenpeace" in the Apple App Store :P :P

![schermata 2018-11-19 alle 16 14 42](https://user-images.githubusercontent.com/7761650/48715887-58ea8400-ec16-11e8-8ac7-1394f25883d3.png)

**Comment by comzeradd** [comment]
Hi @45kb! Sorry for the really late reply, but this repo was inactive and recently re-purposed.

Right now we are not considering of building a desktop app, it may seem simple but it would need significant effort considering the complexity of the platform and the amount of website relying on that. But thanks for the idea :green_heart: Building an electron app is potentially something we could use for certain campaigns in the future.
