### ISSUE TITLE
Manual of style for P4 Documentation

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#141]
## Brief summary of task:
Create a manual of style for the P4 Documentation, that can easily be followed by all current and future specialists that write documentation. 

### Tasks:
- establish set up tone and voice
- indications for creation of accessible content
- write indications for writing content for the web
- write indications for writing content for international audiences

### Example of similar work:
-  [A11y Style Guide](https://a11y-style-guide.com/style-guide/)
-    [Microsoft Manual of Style (4th Addition)](https://ptgmedia.pearsoncmg.com/images/9780735648715/samplepages/9780735648715.pdf)
-   [A List Apart Style Guide](https://alistapart.com/about/style-guide/)

## Help:
You can always reach out to the Planet4 team at planet4-pm-group@greenpeace.org if you have a question. -->

**Comment by PadminiRai** [comment]
I'd like to work on this issue.

**Comment by andradaradu** [comment]
Hi @PadminiRai and thanks for reaching out to us! 
Could you please send us an email to planet4-pm-group@greenpeace.org email address to try set up a meeting so we can catch up on this? 

Thanks!
