### ISSUE TITLE
[Handbook] Create page layouts/templates

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#142]
## Brief summary of task:
Create layouts or templates for P4 documentation

### Tasks:
- create layouts for pages - Handbook
- create layouts for posts - Handbook

### Example of similar work:
Title:
Subtitle:
Table of contents:
Features:
Visuals:
Additional resources

## Help:
You can always reach out to the Planet4 team at planet4-pm-group@greenpeace.org if you have a question. -->

**Comment by Anita-ihuman** [comment]
@andradaradu I would like to take up this task, but I could use some help fixing this.

**Comment by andradaradu** [comment]
Hi @Anita-ihuman and thanks for reaching out to us! 
Could you please send us an email to planet4-pm-group@greenpeace.org email address to try set up a meeting so we can catch up on this? 

Thanks!

**Comment by andradaradu** [comment]
Hi @Anita-ihuman are you still interested in working on this? Let me know, we did a lot of progress, I just need the help of a designer to make sure the templates I did would literally look good 
![Child page (level 2)](https://user-images.githubusercontent.com/67154062/131879657-cc8fadd7-4ecf-44a5-b49a-c4f717b849f1.jpg)
![child page (level 3)](https://user-images.githubusercontent.com/67154062/131879667-defccfbc-b76b-4027-935e-4c24b70aca88.jpg)
![parent page](https://user-images.githubusercontent.com/67154062/131879859-3b990629-74ab-4bb6-8cc9-754016a55ce1.png)
