### ISSUE TITLE
PLANET-5646 Handbook: review Pablo's recommendation #1 - Removing the top bar and moving the search to the sidebar

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#143]
## Brief summary of task:

As suggested by Pablo Cuadrado and described in [PLANET-4847](https://github.com/greenpeace/planet4/issues/49) we are exploring a more user-friendly Handbook nav. This task is about a UX review of the top bar removal and the move of the search to the sidebar. See Snapshots. 

## Dependencies on other work:

- relates to issue #49 

## Help:
You can always reach out to the Planet4 team at planet4-pm-group@greenpeace.org if you have a question. -->

![image](https://user-images.githubusercontent.com/67154062/115602790-02eb0080-a2e8-11eb-9532-d48e9386fdb7.png)

**Comment by shruti1421** [comment]
Can I work on this issue?

**Comment by andradaradu** [comment]
Hi @shruti1421 and thanks for reaching out to us! 
Could you please send us an email to planet4-pm-group@greenpeace.org email address to try set up a meeting so we can catch up on this? 

Thanks!

**Comment by andradaradu** [comment]
duplicate of #49

**Comment by suzi-greenpeace** [comment]
hey @andradaradu - I thought we're moving the navigation to the top... doesn't that make this irrelevant now?

**Comment by andradaradu** [comment]
yes, you are right @suzi-greenpeace  
Gonna close this one. thanks for the sharp eye.
