### ISSUE TITLE
PLANET-5649: Handbook: propose new search bar placement (esp. desktop version)

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#147]
## Brief summary of task:

In desktop screens there is unnecessary space between the header and the search bar, whihc is also misaligned,.

We should align the GP logo with the search bar, reducing the overall blue overlay, see scrennshot and eventually align with William Morris-Julien for design specs

UPDATE:

-  Pablo Cuadrado started already doing some design and proposing alternative placement of search bar in left-side nav (see Snap)
-   We should test usability, especially in relation to the already long left-side nav, to facilitate content access and consumption.
-  Desktop is priority, but tests should also happen in tablet and mobile screens

## Help:

You can always reach out to the Planet4 team at planet4-pm-group@greenpeace.org if you have a question. -->

![image](https://user-images.githubusercontent.com/67154062/115731737-0c2fa800-a390-11eb-8104-8308c826b7cf.png)
![image](https://user-images.githubusercontent.com/67154062/115731772-12be1f80-a390-11eb-9e73-de7eadbaeded.png)

**Comment by shruti1421** [comment]
Can I work on this issue?

**Comment by andradaradu** [comment]
Hi @shruti1421!
We will be reaching out to you soon to set up a call and see exactly which tickets you could take over!

Thank you once again for your interest in the project!
