### ISSUE TITLE
PLANET-5761 Remove jQuery from search.js

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#152]
Rewrite all jquery code in `assets/src/js/search.js` (in [master-theme](https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/js/search.js)) with vanilla JS.

**Components**

`setupSearch()` manages search request and appearance. 

```
Reporter: fhernand
Sections: Performance
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Thanks @himanshu007-creator 💚

**Comment by artze** [comment]
Hi, I can take on this issue!

**Comment by mleray** [comment]
> Hi, I can take on this issue!

Hi @artze, thank you so much for wanting to help out 💚 But we actually started working on this already, and it's currently on hold because of some problems that have been reported regarding our search function. Hopefully you can find another issue that inspires you!

**Comment by comzeradd** [comment]
Done in https://github.com/greenpeace/planet4-master-theme/pull/1564
