### ISSUE TITLE
Align colors in the Handbook with Design System

### ISSUE THREAD

**Issue by andradaradu** [greenpeace/planet4#161]
### Brief summary of task:

Consider reducing the number of colours text can have. Define 1 colour each for: normal text and headings, text that is a link. For example in https://planet4.greenpeace.org/content/ there are several text colours (intro text is black, intro links are light blue, hashtags are yellow, box text is white, footer text is 3 shades of blue).

### Relevant documentation:

[Planet 4 Design System](https://p4-designsystem.greenpeace.org/05f6e9516/p/76cd7b-planet-4-design-system)

### Other resources:

https://jira.greenpeace.org/browse/PLANET-6215

**Comment by Rishika-7** [comment]
Hey, I'd like to work on this issue! Can you assign it to me?

**Comment by jenniferca** [comment]
@Rishika-7 - Please work on this issue. Leaving a comment like you just did claims this issue as yours.

**Comment by Inwerpsel** [comment]
@Rishika-7 It looks like this issue might be missing some information. I'll check what the correct specs are, but feel free to have a look already.

**Comment by Rishika-7** [comment]
@Inwerpsel Yes, I actually went through the issue, checked the handbook example, and looked for the color specs in the design document. But they seem to be aligned with the use of the color which was mentioned in the design document. It'd be great if you could clarify a bit for me about what needs to be done. Thanks

**Comment by Inwerpsel** [comment]
@Rishika-7 I discussed this with @andradaradu and the ticket currently does not have a design for the intended result, only a qualitative description that is a bit vague. So maybe it's not the best one to pick up, sorry about that, are there any other tickets you would like to pick up?

**Comment by Rishika-7** [comment]
@Inwerpsel I understand, I am still looking for some other easy ticket that is unassigned. Since I am a newbie, I am actually unaware of a lot of things and how I should work.
