### ISSUE TITLE
PLANET-6405 PDF link/button icons not showing in later shown search results

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#166]
In the search results you can get some PDF documents which they should have the PDF link and button icons. The first search results do have them as expected, but the ones that are hidden at first and shown only when scrolling or clicking on the "Show more results" button don't (see screenshot).

[Page example](https://www-dev.greenpeace.org/international/?s=ocean&orderby=_score&f%5Bctype%5D%5BDocument%5D=1)

**Screenshots**
![Screenshot](https://jira.greenpeace.org/secure/attachment/32931/Screenshot+2021-09-21+at+10.46.11.png)

```
Reporter: mleray
Sections: Search
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

JIRA Ticket: https://jira.greenpeace.org/browse/PLANET-6405

**Comment by yehee** [comment]
@planet-4 I'd like to take on this issue, but I couldn't seem to find any posts with documents attached.
![Screen Shot 2021-10-01 at 9 42 09 AM](https://user-images.githubusercontent.com/28884850/135657205-2e9d0a15-67dd-4550-8a3d-abac528de61c.png)

This is the link I am looking at currently: https://www.greenpeace.org/international/?s=&orderby=_score

I might be looking at the wrong place, could you please have a look? Thank you!

**Comment by GP-Dan-Tovbein** [comment]
Hi @yehee I'll take a look and keep you posted

**Comment by comzeradd** [comment]
The search query linked in the description seems to work. The first results have the icon, but when you load more the icon is missing.

https://www-dev.greenpeace.org/international/?s=ocean&orderby=_score&f%5Bctype%5D%5BDocument%5D=1

**Comment by yehee** [comment]
@comzeradd Thanks a lot for providing me with the link! It seems like the posts have not been properly processed when more results are fetched. Specifically, [this](https://github.com/greenpeace/planet4-master-theme/blob/dba06f0e2b7878ba176cab27e406be119dfb8dd9/assets/src/js/pdf_icon.js#L15) is where the `pdf-link` is added to the class names. This is done prior to calling `setupSearch` [here](https://github.com/greenpeace/planet4-master-theme/blob/dba06f0e2b7878ba176cab27e406be119dfb8dd9/assets/src/js/app.js#L25-L26) in the main app. I'm thinking if we could process the response prior to appending it in [here](https://github.com/greenpeace/planet4-master-theme/blob/90c9c38419475cf51b5023bd3195ac816487e1cb/assets/src/js/search.js#L95), we should be able to see the PDF icon.

Let me know what you think and how I could test it locally to make sure that the proposed solution works as expected. Thank you!

**Comment by artze** [comment]
@comzeradd @yehee 

if this issue isn't currently being worked on, I can take this up. Let me know!

**Comment by yehee** [comment]
@artze Please go ahead as I do not have enough bandwidth right now to work on the issue. Thanks for the help :)

**Comment by mleray** [comment]
Fixed by https://github.com/greenpeace/planet4-master-theme/pull/1791
