### ISSUE TITLE
PLANET-6387 Make import/export functionality work for all post types

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#167]
We currently have a relatively advanced import/export functionality that unfortunately is only implemented for the "Campaign" post type, only a small fraction of our content.

Luckily it seems that supporting other types is only a matter of removing the check for the post type. There is a [quick draft PR](https://github.com/greenpeace/planet4-master-theme/pull/1447) where it seems to work already, except for the image import. Needs more testing.

```
Reporter: pvincent
Sections: Admin Panel
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Done at https://github.com/greenpeace/planet4-master-theme/pull/1447
