### ISSUE TITLE
PLANET-6154 Disable sync of archived posts to ElasticSearch if archived posts are never included in search

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#169]
Currently we always sync the p3 archived posts to ElasticSearch, even when these are set to never be returned from the search results. In a lot of cases this more than doubles the total amount of data synced to ES, putting unnecessary strain on the cluster and making a full sync a lot slower. We can check the option at sync time and exclude the whole "archive" type if it's turned off for logged in users.

**Tasks**
- Skip indexing archived content if Archive feature flag is off. Add a notice for admins to re-sync the ES index.
- Investigate triggering ES sync when feature flag is turned on. Alternatively we can add a tip for admins to trigger a sync manually if they enable the feature.

```
Reporter: pvincent
Sections: Search, Technical Debt
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Done in https://github.com/greenpeace/planet4-master-theme/pull/1661
