### ISSUE TITLE
PLANET-6000 Images with links open the link in a new tab and the lightbox in the old tab simultaneously.

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#171]
When a user creates an image with a link, the link opens in a new tab and the Lightbox appears in the old tab simultaneously. 

It would be nice to automatically ignore the lightbox if the image has a link. Let's check if we can consistently detect that.

**Tasks**
- Don't enable Lightbox when the Image has a link

```
Reporter: pcuadrad
Sections: Styling/Theme
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

JIRA ticket: https://jira.greenpeace.org/browse/PLANET-6000

**Comment by aditi977** [comment]
I can try to work on this issue

**Comment by GP-Dan-Tovbein** [comment]
Go for it :muscle:

**Comment by comzeradd** [comment]
We had some time to work on that, and it's now fixed at https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/759/commits/4e11dcb334be1817a3cb21147842653776685127
