### ISSUE TITLE
Setting up development environment for Apple Silicon Mac M1

### ISSUE THREAD

**Issue by fatchild** [greenpeace/planet4#180]
### Where did you find the bug?

running   
`make dev`

### What went wrong?

**Development Environment setup issues with MacM1 chip + Docker for planet 4**   
Currently - `ERROR: php-fpm is not running`

### Here's the problem:

I have run into issues with getting the development environment up and running based on the instructions in this documentation...   
https://support.greenpeace.org/planet4/development/installation#fixing-make-dev-errors.  

**Previous Issues**
I have overcome 1 issue which is a fairly common MacM1 + Docker issue with platform type and mySQL.  
To solve this you need to run the following commands...   
`softwareupdate --install-rosetta`   
`export DOCKER_DEFAULT_PLATFORM=linux/amd64`   

**Current Issues**
However, the issue I am struggling with is the php container. I get the following logs...   

```
Waiting for services to start .................
7497a2f39fe1   gcr.io/planet-4-151612/wordpress:main   "/app/bin/entrypoint…"   2 minutes ago   Exited (1) 23 seconds ago                                                                                                                         planet4dockercompose_php-fpm_1

php-fpm_1    | <?php //TEST-DATA-ONLY
php-fpm_1    | phpinfo();
php-fpm_1    |   * [WARNING] Attempting to continue ...
php-fpm_1    |   * Setting permissions of /app to app...
php-fpm_1    |   * WP_DB_HOST         db
php-fpm_1    |   * WP_DB_NAME         planet4_dev
php-fpm_1    |   * WP_DB_USER         planet4
php-fpm_1    |   * WP_DB_PREFIX           wp_
php-fpm_1    |   * Installing Wordpress for site www.planet4.test ...
php-fpm_1    |   * Checkout: https://github.com/greenpeace/planet4-base:main
php-fpm_1    | + git config --system --add safe.directory /app/source
php-fpm_1    | + git init
php-fpm_1    | Initialized empty Git repository in /app/source/.git/
php-fpm_1    | + git remote add origin https://github.com/greenpeace/planet4-base
php-fpm_1    | + git fetch --tags
php-fpm_1    | fatal: unable to access 'https://github.com/greenpeace/planet4-base/': Could not resolve host: github.com
php-fpm_1    | *** /etc/my_init.d/20_install_wordpress.sh failed with status 128
php-fpm_1    |
php-fpm_1    | *** Killing all processes...
php-fpm_1    | Jul 12 14:21:19 7497a2f39fe1 syslog-ng[148]: syslog-ng shutting down; version='3.13.2'

ERROR: php-fpm is not running

make[1]: *** [Makefile:264: up] Error 1
make: *** [Makefile:238: run] Error 2
```

I am unsure of where to look for info in this and wonder if anyone has managed to get this running on an M1 chip.

**System info**
MacBook Air (M1, 2020)
Chip Apple M1
MacOS Monterey 12.4
Docker version 20.10.8
docker-compose version 1.29.2

**Comment by fatchild** [comment]
Once this is solved (assuming it is an issue and not user error), it would be great to add a new tab to the documentation for M1 users specifically.

**Comment by lithrel** [comment]
Hi :wave:  We indeed have at least 2 people on M1 running this, I added a (very small) M1 section just today https://support.greenpeace.org/planet4/development/installation#m1-architecture
The gist of it is you also need to set the redis image `REDIS_IMAGE=arm64v8/redis:4-stretch`. Just run `make clean` before trying to install again.
But for the connection issue you have there in the container `Could not resolve host: github.com`, I'm not sure what could be done. You could try a different dns resolver with `DNS_RESOLVER=` maybe ?

**Comment by comzeradd** [comment]
Closing this as we have a [new development environment](https://github.com/greenpeace/planet4-develop) now that seems to work more reliably on Apple silicon.
