### ISSUE TITLE
make video tutorial about github

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#2]
We decided to use Github to store:
* Issues reported by the community
* Backlog items
* Items the team needs help with
* Items that are not priority to the team

This ticket is to make a short video to show the team how to file issues.

**Comment by IlBrizzo** [comment]
Ciao @LauraHilliger will delete this right away

**Comment by datawebbie** [comment]
It's great to see you guys are using GitHub for issue tracking and code sharing for this project. Now we can all contribute easily.
