### ISSUE TITLE
Add P4 team to Greenpeace org

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#23]
As I find their user names, I'm adding P4 track leads and community folks as contributors and maintainers to this repo. However, I can't assign them tickets. I think they need to be added to the Global Org?

**Comment by comzeradd** [comment]
@all-contributors add lithrel for code

**Comment by comzeradd** [comment]
@all-contributors add pablocubico for code

**Comment by comzeradd** [comment]
@all-contributors add dpivo for code

**Comment by comzeradd** [comment]
@all-contributors add Inwerpsel for code

**Comment by comzeradd** [comment]
@all-contributors add mleray for code

**Comment by comzeradd** [comment]
@all-contributors add sagarsdeshmukh for code

**Comment by comzeradd** [comment]
@all-contributors add dpivo for code

**Comment by comzeradd** [comment]
@all-contributors add mleray for code

**Comment by comzeradd** [comment]
@all-contributors add lithrel for code

**Comment by comzeradd** [comment]
@all-contributors add pablocubico for code

**Comment by comzeradd** [comment]
@all-contributors add Inwerpsel for code

**Comment by comzeradd** [comment]
@all-contributors add jencub for infrastructure

**Comment by comzeradd** [comment]
@all-contributors add magalifatome for design

**Comment by comzeradd** [comment]
@all-contributors add WillMorrisJulien for design

**Comment by LauraHilliger** [comment]
@comzeradd AWESOME that you're adding the team with the  bot. Definitely keep that up, friendly faces are friendly. 

Can you also add P4 team to the Greenpeace organization? Because I can't assign Will and Luca tickets (haven't checked other folks yet)

**Comment by comzeradd** [comment]
@all-contributors add jmarubay for data

**Comment by comzeradd** [comment]
@all-contributors add jmarubay for Data

**Comment by LauraHilliger** [comment]
@all-contributors add @jmarubay for data

**Comment by comzeradd** [comment]
I did the addition manually bd6519b05e293a48dabfc6dd32c54e2ace5434bf

**Comment by LauraHilliger** [comment]
@all-contributors add tolen for ideas
