### ISSUE TITLE
Update code of conduct with email

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#41]
Need to add the moderation email to the CoC: https://github.com/greenpeace/planet4/blob/master/CODE_OF_CONDUCT.md

**Comment by dajbelshaw** [comment]
Nudging this as it's important.

**Comment by LauraHilliger** [comment]
@IlBrizzo Ok, we should link to the full Code of Conduct sent in Sandrine's email:

https://drive.google.com/file/d/18BvOe-2hIuRAfNvKNX5nuOnxIPwzONKj/view

We still need a group email (conduct@greenpeace.org or similar) that forwards to the 4 International Persons of Trust.

**Comment by IlBrizzo** [comment]
Hello and thank you @becha42 for your PR! After we chatted with Sandine and the IPOTs, we agreed that for now I will add ,my email for the moment (I am a certified person of trust), while we also find a female P4 team member to train as well! Together, we'll act as first contact for eventual CoC violations! 

Also (as next step) I have to create a follow-up ticket to match the parts of the CoC that are apllicable with the GPI Code of Conduct.
