### ISSUE TITLE
PLANET-5215 Allow customization of tag page redirect handling

### ISSUE THREAD

**Issue by stduerre** [greenpeace/planet4#46]
Currently, when a tag page is loaded, the master theme checks if a "redirect page" is defined. If there is one, it fetches it's content for display instead of auto generating a tag page.

I'd like to have the ability to change this behavior in child themes/plugins to actually redirect to the URL of the redirect page instead of generating the output right away. 

A possible solution would be to add an action hook before the output is generated.

**Comment by comzeradd** [comment]
Thanks for the contribution. Yes, that make sense, so we can preserve the default behavior but give the ability for NROs to override it
