### ISSUE TITLE
PLANET-2282 Rework the handbook sitemap

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#48]
# Brief summary of task:
Handbook sitemap should be changed > https://planet4.greenpeace.org/handbook-sitemap/
It should show page parenting, and not only Act (Handbook) and Explore (Implement), but the entire sitemap

## Objectives of task:
* Act >> Should become Actions
* Explore >> Implement (and maybe not have it alphabetically ordered but following the left-side navigation at level 1?)
* About Greenpeace >> Should pull out all #Tag pages (they are not relevant to one specific Issue page like in P4, but span across sections)
* Articles >> Should be removed

# Relevant documentation:
https://github.com/greenpeace/planet4-child-theme-handbook
https://jira.greenpeace.org/browse/PLANET-2282

## Other resources:
https://support.greenpeace.org/planet4/

# Help:
You can always [reach out to the Planet4 team](https://groups.google.com/u/1/a/greenpeace.org/g/planet4-group) if you have a question. Or comment here!

![image](https://user-images.githubusercontent.com/539017/85018899-38760900-b16e-11ea-83eb-b99bd4daea37.png)

**Comment by comzeradd** [comment]
Fixed at greenpeace/planet4-child-theme-handbook#21
