### ISSUE TITLE
PLANET-4847 Review Handbook UX Removing the top bar and moving the search to the sidebar

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#49]
# Brief summary of task:
In desktop screens there is unnecessary space between the header and the search bar, which is also misaligned,.

We should align the GP logo with the search bar, reducing the overall blue overlay, see scrennshot and eventually align with @WillMorrisJulien for design specs

As suggested by @pablocubico, we are exploring a more user-friendly Handbook nav. This task is about a UX review of the top bar removal and the move of the search to the sidebar. See Snapshots. 

## Objectives of task:
* Review suggestion and provide input
* We should test usability, especially in relation to the already long left-side nav, to facilitate content access and consumption.
* Desktop is priority, but tests should also happen in tablet and mobile screens

# Relevant documentation:
https://planet4.greenpeace.org/

# Estimated length of task:
1 hour

# Help:
You can always [reach out to the Planet4 team](https://groups.google.com/u/1/a/greenpeace.org/g/planet4-group) if you have a question.

![image](https://user-images.githubusercontent.com/539017/85019356-fb5e4680-b16e-11ea-8780-2fe55341114f.png)

![image](https://user-images.githubusercontent.com/539017/85019376-04e7ae80-b16f-11ea-841f-dec2f1d9540c.png)

![image](https://user-images.githubusercontent.com/539017/85019394-103ada00-b16f-11ea-8c4e-505318ddcf9d.png)

**Comment by WillMorrisJulien** [comment]
Thanks @LauraHilliger

**Comment by Rukmini-Meda** [comment]
@LauraHilliger @WillMorrisJulien Can I take up this issue?

**Comment by andradaradu** [comment]
Hi @Rukmini-Meda !
Thank you so much for reaching out and for your interest in sharing some of your super powers to build a better web. As a next step, do you mind filling this form http://bit.ly/P4contribute?
