### ISSUE TITLE
PLANET-4848 Making the Handbook sidebar sections collapsible

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#50]
# Brief summary of task:
As suggested by @pablocubico, we are exploring a more user-friendly Handbook nav. This task is about a UX review of the option to making the sidebar sections collapsible, so all elements on the sidebar (logo + search + menu) stay fixed as you scroll. 

## Objectives of task:
review the option and give UX input

# Relevant documentation:
https://planet4.greenpeace.org/

# Estimated length of task:
1 hour

# Help:
You can always [reach out to the Planet4 team](https://groups.google.com/u/1/a/greenpeace.org/g/planet4-group) if you have a question. Or comment here!

**Comment by aparnaabraham** [comment]
Hi, I would like to work on this issue

**Comment by andradaradu** [comment]
Hi @aparnaabraham and thanks for reaching out to us! 
Could you please send us an email to planet4-pm-group@greenpeace.org email address to try set up a meeting so we can catch up on this? 

Thanks!

**Comment by suzi-greenpeace** [comment]
I think that since we're going with a single-level, header nav for now, this is unnecessary.
