### ISSUE TITLE
PLANET-4850 Adding syntax colouring for code blocks 

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#52]
# Brief summary of task:
This task is about adding adding syntax coloring for code blocks, to make code embeds more readable. UX advice needed

## Objectives of task:
describe how we should color code blocks / best practices

# NEEDS
An example of a code block. Perhaps @IlBrizzo knows where one is and can add a link so a UX designer sees what it currently looks like?

**Comment by WillMorrisJulien** [comment]
Thanks for this @LauraHilliger I'll pick this up.
