### ISSUE TITLE
Discuss adding a link to Github in P4 footers with p4-council

### ISSUE THREAD

**Issue by LauraHilliger** [greenpeace/planet4#56]
# Brief summary of task:
There is currently no organic route into contributing to P4. For example you would expect a link to the P4 repo (this repo) in the footer of P4-powered sites, but there isn't one. This issue is to suggest that @suzi-greenpeace talks to the P4-Council about the recommendation from [the Architectures of Participation](https://docs.google.com/document/d/1HFUzj4DFd5lKhpHHn_kH-YmSZv0jEuh7JPJdgwKfHwo/edit#).

## Objectives of task:
* Socialize the recommendation to create an organic route to this FOSS project
* Determine whether or not NROs want to have a link to Github in their footer

# Relevant documentation:
 [the Architectures of Participation](https://docs.google.com/document/d/1HFUzj4DFd5lKhpHHn_kH-YmSZv0jEuh7JPJdgwKfHwo/edit#).

**Comment by dajbelshaw** [comment]
![p4-footer](https://user-images.githubusercontent.com/2429426/85402495-b3b33280-b553-11ea-85d2-dab775a9bb8b.png)

For the avoidance of doubt, we're talking about somewhere around the area indicated by the '1' in the above image :smiley:

**Comment by LauraHilliger** [comment]
Another idea from @gingerdude was about adding either a translated version of "how to contribute" page to NRO sites or a link to the handbook page: https://planet4.greenpeace.org/create/contribute/

**Comment by tolen** [comment]
GPI is happy to point potential contributors to the Github! 
You can find it in our footer here: https://www.greenpeace.org/international/
