### ISSUE TITLE
Rework the "Community" handbook page to reflect the P4 Community Strategy 

### ISSUE THREAD

**Issue by IlBrizzo** [greenpeace/planet4#64]
Once we published the Medium post on the Community Strategy, we should take some time to revamp the Community Page in the Handbook ( https://planet4.greenpeace.org/community/) to include: 

- Each Sub-community visions, channels and Onboarding paths 
- Updated links to Documentation and Videos
- Updated list of the Community Calls (should we split by Sub-track?) 
- Proper design (Should it be a /handbook/  take action page?)

**Comment by LauraHilliger** [comment]
DONE! Any adjustments or can we close this ticket? https://planet4.greenpeace.org/community/

**Comment by IlBrizzo** [comment]
Finally found the time to update it! Inserted all tracks + links to github / CoC and so on!
