### ISSUE TITLE
PLANET-5235 Header Carousel: Header text cuts off at 32 characters

### ISSUE THREAD

**Issue by comzeradd** [greenpeace/planet4#65]
# Brief summary of task:
When placing text in the header field of the header carousel the text on the front end cuts off at 32 characters yet the counter indicates that it has a 40 character maximum.

## Objectives of task:
- Fix the backend character counter to match the 32 limit

**Comment by lithrel** [comment]
Closed by https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/355
