### ISSUE TITLE
PLANET-5322 Conform our shell scripts to Google Styleguide using shfmt

### ISSUE THREAD

**Issue by comzeradd** [greenpeace/planet4#72]
# Brief summary of task:
For consistency we can follow [Google Shell Script Styleguide](https://google.github.io/styleguide/shellguide.html) in all of our shell scripts. This is mainly for planet4-builder and planet4-circleci repositories, that hold most of our scripts.

## Objectives of task:
To enforce that we can use [shfmt](https://github.com/mvdan/sh) to adjust our current scripts but also lint future changes and additions.

*Tasks*
- Run shfmt to all of our scripts at these two folders: [builder](https://github.com/greenpeace/planet4-builder/tree/develop/src) and [circleci](https://github.com/greenpeace/planet4-circleci/tree/master/src/circleci-base/scripts).
- Expand our lint job to use shfmt along with shellcheck

**Comment by r0bobo** [comment]
Can I suggest reviewers for the two pull-requests or are the relevant people pinged automatically anyway?

**Comment by comzeradd** [comment]
Thanks @r0bobo :green_heart: I added a few relevant people as reviewers so they get the ping ;)
