### ISSUE TITLE
PLANET-5466 Implement new Accordion block

### ISSUE THREAD

**Issue by comzeradd** [greenpeace/planet4#81]
# Brief summary of task:

As a follow-up of [the idea](https://planet4.greenpeace.org/idea/show-hide-plugin-for-qas/) a new P4 block, codename *"Accordion"* has been designed.

The idea is to have a block that allows collapsible menus, behaving exactly like the "Column" blocks > Tasks Style on mobile.

## Objectives of task:
- Implement the block based on the mock up provided (see below)
- The block should be WYSIWYG in the backend editor
- There should be two extra fields (Title & Description) similar to other blocks
- The block template should use jsx for both frontend and backend
- Add the block in [beta group](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/classes/class-loader.php#L467)

## Screenshots & Mockups

![Cheveron](https://user-images.githubusercontent.com/939357/92375570-f4a9f480-f109-11ea-8d41-a19fa9e1b1ea.jpg)

**Comment by elncetoo** [comment]
So far I have a created a one block that is added for post, pages and  campaigns, but like a p4 block, so It needs to be registered as beta to match the dscr. It has Title & description, and accordion block style that looks according the voted style guide, the content  expands on hover. Problem is the fronendIndex is not visible on the frontend but on the editors frontend only.. and props are not being passed okay.. also I am not sure where this read more button should redirect to(in our nordic use case we use the accordion to provide simple information like FAQ.. also I see that the two working examples are also without button, so I am not sure if it should expand more of this hidden content or to redirect to a page?

**Comment by comzeradd** [comment]
Thanks @elncetoo :green_heart: 

I suggest you push your branch, so we can kick off the discussion on implementation. Regarding the button, this is intended to be optional and it's just something editors can choose to add (pick up text and link). Similar to what we have for the Columns block on the Tasks style (although not WYSIWYG yet).

**Comment by elncetoo** [comment]
I see got`cha ;) I reaalyyy want to fiddle a bit more with it now on my own tbh and i`ll push the latest thing i have today so we can see whats wrong with my code ;)

**Comment by oekeur** [comment]
This can be closed right? :)

**Comment by elncetoo** [comment]
yup :)

**Comment by comzeradd** [comment]
Fixed at greenpeace/planet4-plugin-gutenberg-blocks#440
