### ISSUE TITLE
PLANET-5468 Columns block: Huge image on the 4th column

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#82]
Example: https://www.greenpeace.org/luxembourg/de/sich-informieren/greenpeace/team/

Description of the issue: The 4th image sometimes is huge on 4th column blocks (see screenshots)

**Tasks**
 - 4th Column should be either in the same row or at least not span in full width
 - Long words in first two columns are pushing the content. Could try word-break
 - Or flex-grow attribute

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31608/Capture+d%E2%80%99%C3%A9cran+2020-09-03+%C3%A0+16.07.56+-+Lise+Bockler.png)
![Screenshot](https://jira.greenpeace.org/secure/attachment/31607/Capture+d%E2%80%99%C3%A9cran+2020-09-03+%C3%A0+16.08.04+-+Lise+Bockler.png)
```
Reporter: lbockler
Sections: Block: Columns
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by comzeradd** [comment]
Fixed at greenpeace/planet4-plugin-gutenberg-blocks#400
