### ISSUE TITLE
PLANET-5254 Author page accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#85]
The author page looks generally ok. Some minor issues:

* It reads the name, then the picture has the name as ALT tag so it reads the name tag. It could say "Picture of..." instead.
* The share buttons are read between the picture and the bio, maybe we should render somewhere else in the DOM.

The "posts by" section is ok, we have a few issues with the article teasers (the list of articles), but we'll deal with those in separate tickets, maybe as part of the Articles Block accessibility ticket.

```
Reporter: pcuadrad
Sections: 
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-master-theme/pull/1220
