### ISSUE TITLE
PLANET-5256 "Post type + Hashtag" component Accessibility

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#86]
We have this tiny widget in some places, that looks like this:

People · #Consumption #Oceans

This is in some [page headers](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/blocks/header.twig#L18), and [search](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/single.twig#L27)/[article](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/master/assets/src/blocks/Articles/ArticlePreview.js) teasers. The mid dot is read aloud, make sure the mid dot char is hidden to Screen Readers using **aria-hidden** and check the Hashtag Accessibility [ticket](https://jira.greenpeace.org/browse/PLANET-5229) to deal with some potential issues with Hashtags. The [dot](https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/scss/layout/_breadcrumbs.scss#L23) is currently a `:before` CSS pseudo-element, so this probably needs to be refactored.

**Notes:**
For the pseudo element we might be able to solve this with [media queries](https://stackoverflow.com/questions/26634156/can-i-prevent-after-pseudo-element-from-being-read-by-screen-readers) so we don't have to change the markup.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31374/Captura+de+pantalla+2020-06-28+a+la%28s%29+18.54.47.png)
```
Reporter: pcuadrad
Sections: 
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks), [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

### Testing
- You can test the Articles block by adding it to a page and testing it with a screen reader (it should also be present on your local [homepage](http://www.planet4.test/)). You can check the [docs](https://planet4.greenpeace.org/act/articles/) for more details on how the block works.
- For the page headers, you can check some posts on your local (for example [this one](http://www.planet4.test/act/vestibulum-leo-libero/))

**Comment by akankshakmr174** [comment]
I can work on this! :)

**Comment by aliya-rahmani** [comment]
@akankshakmr174 go ahead and make a PR for this issue.

**Comment by akankshakmr174** [comment]
@aliya-rahmani This issue seems to be resolved. Checked with voiceover and NVDA on Chrome.
