### ISSUE TITLE
PLANET-5211 Home page Accessibility: Navigation bar and "Skip to..." links.

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#88]
Maks sure navigation flow sounds good on a screen reader.

Tasks:
 * Hide "Skip to" links to the SR using aria-hidden.
 * Search: Both the input and the search icon are read as "Search". Make the input more descriptive using aria-label or hide tha search icon to the SR or add a label as "Press return/enter to search" or "click to search".
 * Countries list, make sure it works well, is browsable, and it has proper aria tags to deal with the transition (the big menu appearing).
* Make sure new text is translatable.

 

```
Reporter: pcuadrad
Sections: Navigation
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-master-theme/pull/1214
