### ISSUE TITLE
PLANET-5198 Carousel Header: 'https://' error message not added 

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#91]
Recently, all blocks with custom fields have been introduced a message to display the need of the "https://" parameter for custom URLs. However, this block was not updated resulting in links not working if they are not updated. 

**Tasks**
- Replicate validation code/functionality from other blocks for the URL fields
 

```
Reporter: aradu
Sections: Block: Carousel Header, Gutenberg
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by mleray** [comment]
Fixed with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/483
