### ISSUE TITLE
PLANET-5331 Articles block: Scheduled Posts are not appearing once published

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#92]
An Editor schedules a Post (in this case, a PR) to auto-publish at a later date/time. When the schedule date/time arrives the Post goes live. The Post **should** appear on the front-end of the website in the Articles block. This is not happening.

The Post does appear on the Posts list, as it should. It isn't until the Admin purges the cache that the Post appears in the Articles block.

**Tasks**
- We recently converted the Article block to WYSIWYG. Check if the problem still occurs and investigate a fix.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31472/Articles-block-page+-+Kelli+Tolen.png)
![Screenshot](https://jira.greenpeace.org/secure/attachment/31473/Post-type-page+-+Kelli+Tolen.png)
```
Reporter: ktolen
Sections: Block: Articles
```
Potentially affected repositories: [planet4-plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks)

**Comment by janocano** [comment]
I can see my post on the main page, but not on the press center page

**Comment by janocano** [comment]
After further looking into I don't think this is a bug anymore. I can see my scheduled posts pop up as scheduled.

**Comment by janocano** [comment]
I have tried multiple times, if this is still a bug it would need more specifications. What exactly caused this? Are there examples of times that this happened? 

I would close this issue.

**Comment by SanmithraMudigonda** [comment]
Task was to investigate if the issue still persists. Bug could not be reproduced, I think it is resolved after converting to WYSIWYG.
