### ISSUE TITLE
PLANET-5386 YouTube embed: URL parameters not working

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#93]
It's common practice to add `?rel=0` parameter to YT URLs to prevent YouTube from showing related/suggested video from another YT channel (other than our own) when a video ends. However this does not work when using the YT or Embed blocks.

The editor must chose between allowing YT suggested videos and retain the full-width/responsive height design OR suppress the suggested videos by using the HTML block w/ YT's embed code and give up the full-screen/responsive height design.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31513/YouTube+embed+-+Kelli+Tolen.png)
```
Reporter: ktolen
Sections: Gutenberg
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-master-theme/pull/1258
