### ISSUE TITLE
PLANET-4861 Adjust search sorting options

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#94]
The scope of this ticket is to add a "Less recent" filter to search for older creation date of content first. This way users are able to search for archive content easier.

**Tasks**
- Add sort option called "Oldest"
- Rename option "Most recent" as "Newest"
- Make sure string is translatable
- Make sure that archived content should be sorted

```
Reporter: mfatome
Sections: Search
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by cnmunn** [comment]
hey! My name is chris (they/them) and i wanna start contributing this project and work on this as my first ticket. i cloned the repo already and installed docker and im gonna start working on this request now : ) id love to meet some new people working on this project and learn more about it! this is my first open source contribution so any tips/advice/people to collab with would be awesome. i currently am working as a web dev intern and i wanna combine my coding skills with my interests in climate activism to help greenpeace out! so excited to be working on this project, hopefully i can meet some people to help me out if i hit any snags with this one!

**Comment by comzeradd** [comment]
Hi Chris, thank you for reaching out and your interest to contribute :green_heart: 

I'll assign you this ticket, but feel free also to look around the rest of issues, and of course the codebase. You can check our [detailed technical documentation](https://support.greenpeace.org/planet4/), which also includes how to setup your local development environment among other things.

**Comment by suzi-greenpeace** [comment]
Hi @cnmunn ! thanks for finding us! Like Nikos said above, feel free to check out our open issues and read up on the documentation of the project. Could you also fill out this form and tell us a bit more about yourself? http://bit.ly/P4contribute thanks! we'll be in touch.

**Comment by comzeradd** [comment]
This was done in https://github.com/greenpeace/planet4-master-theme/pull/1241
