### ISSUE TITLE
Match Code of Conduct with the Greenpeace International Code of Conduct

### ISSUE THREAD

**Issue by IlBrizzo** [greenpeace/planet4#97]
As part of our commitment to respect and protect volunteers and contributors, we should update this github P4 CoC https://github.com/greenpeace/planet4/blob/master/CODE_OF_CONDUCT.md to match the values of the Greenpeace International Code Of Conduct that all staff must sign to work at Greenpeace. 

### Objectives of task:
match the relevant parts of the P4 Github CoC with the relevant components of the GPI CoC  

## Relevant documentation:
Need to find the GPI CoC and upload it in Drive - get the link and push it here 

### Other resources:
Model of CoC (2018 - need to check if it's the latest enforced one) https://drive.google.com/file/d/18BvOe-2hIuRAfNvKNX5nuOnxIPwzONKj/view 

## Estimated length of task:
2h

### Example of similar work:

https://github.com/greenpeace/planet4/issues/41

**Comment by unnati2201** [comment]
Hey,
I want to work on this.
