### ISSUE TITLE
PLANET-5516 Author bio translation displaying wrong language

### ISSUE THREAD

**Issue by planet-4** [greenpeace/planet4#99]
Example page: https://www.greenpeace.org/canada/fr/histoires/42536/discours-du-trone-les-liberaux-doivent-renoncer-a-sauver-lindustrie-nucleaire/

Description of the issue: On the French version of this blog post, the author's bio is displayed in English even though a French translation of the bio is set up. If you click to read more of the bio, it displays correctly in French. I have noticed a similar issue with other authors, i.e. bio displaying in French when it should be in English for an English post.

**Screenshots**

![Screenshot](https://jira.greenpeace.org/secure/attachment/31702/Screen+Shot+2020-09-24+at+9.21.59+AM+-+Lucas+Silbernagel.png)
```
Reporter: lsilbern
Sections: Translations
```
Potentially affected repositories: [planet4-master-theme](https://github.com/greenpeace/planet4-master-theme)

**Comment by comzeradd** [comment]
Fixed at https://github.com/greenpeace/planet4-master-theme/pull/1207
